# Generated by Django 3.2.9 on 2021-12-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefiValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_vote_pubkey', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(default=50)),
            ],
        ),
    ]
