# Generated by Django 3.2.9 on 2021-12-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solanavalidator',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
