# Generated by Django 3.2.9 on 2021-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_solanavalidator_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solanavalidator',
            name='display_name',
            field=models.CharField(default='validator_display_name', max_length=50),
            preserve_default=False,
        ),
    ]
