# Generated by Django 3.2.9 on 2021-12-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_solanavalidator_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefiWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_pubkey', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
