# Generated by Django 4.0 on 2021-12-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_solanawallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='solanawallet',
            name='is_staked',
            field=models.BooleanField(default=False),
        ),
    ]
