# Generated by Django 4.0 on 2021-12-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_solanawallet_is_staked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solanawallet',
            old_name='is_staked',
            new_name='staked',
        ),
    ]
