# Generated by Django 4.0 on 2021-12-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_is_staked_solanawallet_staked'),
    ]

    operations = [
        migrations.AddField(
            model_name='solanavalidator',
            name='defi_network',
            field=models.CharField(default='solana', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solanawallet',
            name='defi_network',
            field=models.CharField(default='solana', max_length=50),
            preserve_default=False,
        ),
    ]
