# Generated by Django 4.0 on 2021-12-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_solanavalidator_defi_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solanavalidator',
            name='defi_network',
            field=models.CharField(default='solana', max_length=50),
        ),
        migrations.AlterField(
            model_name='solanawallet',
            name='defi_network',
            field=models.CharField(default='solana', max_length=50),
        ),
    ]
