# Generated by Django 4.0 on 2021-12-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_solanavalidator_defi_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefiValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_vote_pubkey', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('defi_network', models.CharField(default='solana', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DefiWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_pubkey', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('staked', models.BooleanField(default=False)),
                ('defi_network', models.CharField(default='solana', max_length=50)),
            ],
        ),
    ]
