# Generated by Django 4.0 on 2021-12-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_defivalidator_defiwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defivalidator',
            name='defi_network',
            field=models.CharField(default='solana2', max_length=50),
        ),
    ]
